#!/usr/bin/env bash
# Displays 1-20 aswell as bad luck statements
 
 
n=1
 
while [ $n -lt 21 ];
do
    echo $n
    case $n in
        4)
            echo "bad luck from China" ;;
        9)
            echo "bad luck from Japan" ;;
        17)
            echo "bad luck from Italy" ;;
    esac
    ((n++))
done
